### ISSUE TITLE
implement deep search graph

### ISSUE THREAD

**Issue by VinciGit00** [ScrapeGraphAI/Scrapegraph-ai#260]
**Is your feature request related to a problem? Please describe.**
Implement in a good way the deep search graph

**Describe the solution you'd like**
<img width="565" alt="Screenshot 2024-05-17 alle 10 05 35" src="https://github.com/VinciGit00/Scrapegraph-ai/assets/88108002/025f0e15-1a3c-4d2e-b9a6-b54cd0f97c32">

**Comment by DiTo97** [comment]
@VinciGit00 main question is if any cascading deep search graph should have its own specific config, or even that is propagated $n$ times through the chain

**Comment by mayurdb** [comment]
@VinciGit00  can you please add some details on which are the things you are planning to do on top of what I have contributed?

Based on my experience while implementing and testing the deep search, these are the areas I feel need a lot of attention:
1. Finding out the most relevant links for the search given a large number of links on a webpage
2. Accurately deciding if a webpage has any answer related to the question

**Comment by DiTo97** [comment]
@mayurdb coping with both your points might require having two cascading conditional nodes in each block

one deciding if the information collected by now is enough to answer the initial query; if the answer is negative, and the most relevant links are fetched, the other conditional node should weigh them and decide if there's any additional link that might aid in answering the query with undiscovered information or simply return with incomplete information.

**Comment by f-aguzzi** [comment]
I had a talk with @VinciGit00 a few days ago. Some of the nodes are likely to receive an overhaul to their inner workings, but without any breaking changes to their outer interface. He didn't like the idea of having to add signals right into the base node, at the core of the node system. That's why he rolled back one of @mayurdb's commits.

We then tried to figure out if there could be a way to reimplement deep scraping using the original nodes, without signals nor runtime loops. My initial idea was to use recursion, but the graph engine doesn't seem to handle it well - it would cause stack overflows even with stop conditions in place.

I then considered to readapt Mayur's original idea of iterating on a `fetch/parse/rag/search_link` sequence for each link through a `GraphIterator` - however, instead of using a runtime loop for the _n_ layers, the graph could be pre-built with iteration in the constructor. That way, the resulting graph would still be a tree, without loops, and wouldn't mess with the current graph engine. Vinci suggested to add a conditional node for early returns.

The last thing we need to figure out before implementing this is what conditions to put in place for early return. Ideally, we could implement two modes for the graph:
- a "cheap mode" that returns as soon as any relevant information is found
- an "accurate mode" that keeps on crawling as long as there are relevant links, even if some relevant information has been found at the current level

This is not just deep scraping: if this configuration works - for how inelegant it may be in its current form - it would further prove that @PeriniM's modular system is expressive enough for complex scraping operations.

As for the actual implementation, Vinci asked me to have another talk before writing any code. That will take another couple of days to be possible. I'll be glad to have Mayur as a co-author and/or reviewer.

**Closing note**: _the right-side diagram is wrong_. It's not a chain of deep scrapers, but of graph iterators running deep scrapers. Between each layer of graph iterators, there are merge nodes both for links and answers, and a conditional node to provide an early return. I feel like there's something off with the left diagram too, but I'd need to look at the original drawings we made on paper.

**Comment by DiTo97** [comment]
@f-aguzzi, exchanged some ideas with @VinciGit00 as well; we should collect all thoughts, and devise the most sensible solution without requiring a major refactoring effort from the current modular graph execution engine.

you could get the best of both _cheap_  and _accurate_ modes if you decouple responsibilities.

A very rough pseudo implementation might look like the following, but we have to simplify it, matching our nodes:

```mermaid
stateDiagram-v2
    note left of deep_search_graph
    - base_endpoint
    - max_rounds
    - max_subgraphs
    - user_query
    end note

    state deep_search_graph {
        [*] --> plan_node

        note right of plan_node
        - available_information
        - endpoints
        - rounds
        - user_query
        end note

        state rounds_expired <<choice>>
        state enough_information <<choice>>

        plan_node --> conditional_node_1
        conditional_node_1 --> rounds_expired
        rounds_expired --> conditional_node_2: if rounds LT max_rounds
        rounds_expired --> answer_node : if rounds EQ max_rounds
        conditional_node_2 --> enough_information

        enough_information --> parallel_search_graph: not enough information
        enough_information --> answer_node : enough information

        state parallel_search_graph {
            state fork_state <<fork>>
            state join_state <<join>>
            
            [*] --> rerank_node

            note right of rerank_node
            - missing_information
            - endpoints
            end note

            rerank_node --> fork_state

            note left of fork_state
            - k EQ max_subgraphs
            - top_k_endpoints
            end note

            fork_state --> search_graph_1
            fork_state --> search_graph_2
            fork_state --> search_graph_k

            state search_graph_1 {
                [*] --> fetch_node
                fetch_node --> parse_node
                parse_node --> RAG_node
                RAG_node --> search_node
                search_node --> search_endpoints_node
                search_endpoints_node --> [*]
            }

            search_graph_1 --> join_state
            search_graph_2 --> join_state
            search_graph_k --> join_state
            
            join_state --> reduce_node

            note right of reduce_node
            - information
            - endpoints
            end note

            reduce_node --> [*]
        }

        parallel_search_graph --> plan_node

        answer_node --> [*]
    }
```

**Comment by mayurdb** [comment]
Hi thanks for the explaination. All of these are great ideas, but I would recommend spending a lot more time on the two things I mentioned above:
1. Finding out the most relevant links for the search given a large number of links on a webpage
2. Accurately deciding if a webpage has any answer related to the question

I understand the orchestration also needs a revamp but the deep search would work only as well as the working of the two points above work. So it would be better to get some beta version of the orchestration that you are thinking out (even if it is not perfect) and then focusing on the core problems. Orchestration can then be perfected incrementally.

**Comment by VinciGit00** [comment]
the search link node should modified to return a link with a short description (should do the fetch)

**Comment by DiTo97** [comment]
rerank link node should be a simple vector database on links and descriptions for the time being

**Comment by VinciGit00** [comment]
hi guys look at the new betaaaaaaaaaaaaa
