### ISSUE TITLE
Not match Gemini embeddings model

### ISSUE THREAD

**Issue by lrbmike** [ScrapeGraphAI/Scrapegraph-ai#496]
In `abstract_graph.py` file，to ceate gemini embedder 

``` python       
        elif "gemini" in embedder_params["model"]:
            try:
                models_tokens["gemini"][embedder_params["model"]]
            except KeyError as exc:
                raise KeyError("Model not supported") from exc
            return GoogleGenerativeAIEmbeddings(model=embedder_params["model"])
```

but the embedding model also like `models/embedding-001`, or I want to use the new model `models/text-embedding-004`, and the "gemini" keyword not in the model name.

and I think it's not a good idea to use these way to match all the models, especially using “models_tokens” to standardize each model.

**Comment by f-aguzzi** [comment]
Unfortunately `abstract_graph` is a mess, the most chaotic submodule in the library, and we know it. It will go through through some rounds of refactoring in the upcoming weeks. The first round is #494. Hopefully we'll be able fix this issue soon. Thanks for reporting this.

**Comment by lrbmike** [comment]
I think Langchain framework has also faced similar challenges, and I look forward to a better experience in the new version.

> Unfortunately `abstract_graph` is a mess, the most chaotic submodule in the library, and we know it. It will go through through some rounds of refactoring in the upcoming weeks. The first round is #494. Hopefully we'll be able fix this issue soon. Thanks for reporting this.

**Comment by f-aguzzi** [comment]
A little update on the latest betas: embeddings are not needed anymore in any of the graphs. The `RAGNode` (the only node using embeddings) is now dead code, but we left it in the code base in case it might be needed in the future, and relocated all the embeddings initialization code inside of it, instead of leaving it the `AbstractGraph`.

All of this to say: the bug you reported probably won't be fixed until we find a new use for the `RAGNode`, but it won't bother you anymore because the embeddings will not be used by any graph in the upcoming releases of ScrapeGraphAI.

Thank for your input, thanks for using ScrapeGraph, and let us know in case you have any other problem with the library.

**Comment by lrbmike** [comment]
Great! I'll have a try.

**Comment by lrbmike** [comment]
@f-aguzzi In the latest version v1.12.2, I still found some mistakes with gemini model.

In `abstract_graph.py` file, use "google_genai".
```
        if "gemini" in llm_params["model"]:
            model_name = llm_params["model"].split("/")[-1]
            return handle_model(model_name, "google_genai", model_name)
```

But in `models_tokens.py` file,  still use "gemini" .

**Comment by f-aguzzi** [comment]
> @f-aguzzi In the latest version v1.12.2, I still found some mistakes with gemini model.
> 
> In `abstract_graph.py` file, use "google_genai".
> 
> ```
>         if "gemini" in llm_params["model"]:
>             model_name = llm_params["model"].split("/")[-1]
>             return handle_model(model_name, "google_genai", model_name)
> ```
> 
> But in `models_tokens.py` file, still use "gemini" .

We'll fix this ASAP, thanks for reporting it to us

**Comment by VinciGit00** [comment]
hi please update to the new beta
