### ISSUE TITLE
The Dockerfile doesn't work well

### ISSUE THREAD

**Issue by AmazeQiu** [ScrapeGraphAI/Scrapegraph-ai#540]
### Discussed in https://github.com/ScrapeGraphAI/Scrapegraph-ai/discussions/539

<div type='discussions-op-text'>

<sup>Originally posted by **AmazeQiu** August 12, 2024</sup>
I used the Dockerfile listed in the project to build an image which just didn't work for runing the demo code in README.md.
It still needs more installation about scrapegraphai[burr] and Playwright.

The following Dockerfile works well for me:

``` docker
FROM python:3.11-slim

RUN apt-get update && apt-get upgrade -y

RUN pip install scrapegraphai
RUN pip install scrapegraphai[burr]

RUN python3 -m playwright install-deps
RUN python3 -m playwright install
```

**Comment by f-aguzzi** [comment]
Thanks for your suggestion - the dockerfile hasn't been updated in a while, as we don't really use it in the development.

If you want, you can make a pull request. Otherwise, in a few days someone from the team will include your additions to the dockerfile and credit you as the co-author of the commit.

Let us know if you find anything else that needs fixing or updating. Thanks again for contributing :)

**Comment by AmazeQiu** [comment]
> Thanks for your suggestion - the dockerfile hasn't been updated in a while, as we don't really use it in the development.
> 
> If you want, you can make a pull request. Otherwise, in a few days someone from the team will include your additions to the dockerfile and credit you as the co-author of the commit.
> 
> Let us know if you find anything else that needs fixing or updating. Thanks again for contributing :)

Thanks for replying! I'll make a pull request later   :)
