### ISSUE TITLE
Different prompt_tokens size between Azure OpenAI and OpenAI

### ISSUE THREAD

**Issue by jasonlin0189impv** [ScrapeGraphAI/Scrapegraph-ai#547]
**Describe the bug**
I found same source URL with different gpt source (azure-openai, openai) have different prompt_tokens estimation.
Here is my code:

* OpenAI

```
import os
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

graph_config = {
    "llm": {"api_key": openai_settings.api_key.get_secret_value(), "model": "gpt-4o-mini"},
    "verbose": False,
    "headless": True,
}

smart_scraper_graph = SmartScraperGraph(
    prompt="List me what does the company do, the name and a contact email.",
    source="https://scrapegraphai.com/",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

graph_exec_info = smart_scraper_graph.get_execution_info()
display(prettify_exec_info(graph_exec_info))
```

<img width="1171" alt="截圖 2024-08-14 下午1 13 39" src="https://github.com/user-attachments/assets/edd5eff2-8ccf-4e81-aecb-1218f0f2b527">

* Azure OpenAI

```
import os
from scrapegraphai.graphs import SmartScraperGraph
from scrapegraphai.utils import prettify_exec_info

graph_config = {
    "llm": {
        "model": "azure/gpt-4o-mini",
        "api_key": azure_openai_settings.api_key.get_secret_value(),
        "azure_endpoint": azure_openai_settings.azure_endpoint,
        "azure_deployment": "gpt-4o-mini",
        "api_version": "2024-06-01",
    },
    "verbose": False,
    "headless": True,
}

smart_scraper_graph = SmartScraperGraph(
    prompt="List me what does the company do, the name and a contact email.",
    source="https://scrapegraphai.com/",
    config=graph_config
)

result = smart_scraper_graph.run()
print(result)

graph_exec_info = smart_scraper_graph.get_execution_info()
display(prettify_exec_info(graph_exec_info))
```
<img width="1068" alt="截圖 2024-08-14 下午1 15 56" src="https://github.com/user-attachments/assets/01232bfb-f274-4ec7-9674-29419f39ca48">

**Comment by jasonlin0189impv** [comment]
The difference might be due to missing HTML data in the token calculation. I'm not sure which .py file is responsible for handling the token computation.

**Comment by f-aguzzi** [comment]
Thanks for pointing this out. @VinciGit00 and @DiTo97 did some split experiments a few months ago, that led to the conclusion that GPT models could scrape webpages converted into Markdown quicker than raw HTML pages, while retaining the same quality of the results, unlike all other models tested. Therefore, an OpenAI-specific optimization was added to the library, to turn HTML webpages into Markdown before sending them to the LLM.

Unfortunately, no one in the team thought about adding this same feature to the GPT models hosted on Azure, so thanks for pointing this out. I will make a quick fix, that will be added to the next beta. I'll let you know when it's published, so that you can re-run your experiment and see if now the tokens match.

**Comment by VinciGit00** [comment]
hi please update to the new beta
