### ISSUE TITLE
How does the scraping param, mentioned in the docs, work?

### ISSUE THREAD

**Issue by wesselhuising** [ScrapeGraphAI/Scrapegraph-ai#564]
**Describe the bug**
I wanted to dive into the caching part. In the docs there is a mention of caching, which is a configuration setting for the path to the folder where the cached vars are saved into? Configuring this does not do anything to the folder. I also looked into the examples and found one occurrence of a caching, specifying caching as a boolean. Setting this variable to `True` did not do anything either. I would like to have some sort of caching, is it ready yet?

Thank all for all the work that is being put into this.

**Comment by DiTo97** [comment]
@wesselhuising, will add a couple of pointers:
- the caching parameter was changed from `caching` to `cache_path` in the graph config a while ago, being either a boolean or a string pointing to the desired cache location
- you likely won't see any noticeable difference, as the main purpose for caching was in aiding the RAG node and avoiding re-computation of the vector store of a website page if it had been visited within the cache TTL; but since models got better and we added some clever logic/algorithms to compress the size of a website page's content, as well as us noticing that the responses with the vector store in between were significantly worse in quality, we have removed any RAG nodes from any built-in graph

hope that helps!

**Comment by wesselhuising** [comment]
That makes sense, so as I am using mainly 4o-mini at this point, it will just feed the full DOM to the prompt as its context? Reading your comment, adding any RAG over using the full DOM will yield worse results?

**Comment by DiTo97** [comment]
@wesselhuising not necessarily: 1) might be the DOM but might also be a different, more efficient representation, as I was hinting earlier; 2) depends on the content size if it's being processed all at once or split in chunks, with each being processed individually, and merged at the very end in a unified answer.

what changes is that there's no longer a RAG step, where only a subset of the content is processed depending on semantic similarity; now the whole webpage is processed, either at once or split in chunks, and that's what on average we measured to perform better and more robustly
