### ISSUE TITLE
Package `google-crc32c` does not support Python 12

### ISSUE THREAD

**Issue by qzc438** [ScrapeGraphAI/Scrapegraph-ai#568]
Please see the title described.

**Comment by VinciGit00** [comment]
can you share the code?
is it python 3.12?

**Comment by VinciGit00** [comment]
are you talking about python 3.12?

**Comment by f-aguzzi** [comment]
@qzc438 I noticed this problem too. The warning has been popping up at every use. Maybe we should put an upper limit to the Python version in the project config, we'll see.

@VinciGit00  `crc32c` falls back to the Python-only version when using Python 3.12, instead of calling the C module, and it slows down the library. We should either try pinning back Python 3.11, or finding out what package is importing `crc32c` as a subdependency.

**Comment by LorenzoPaleari** [comment]
The package has been updated yesterday to support python 3.12.
There is no warning anymore

It was imported in the project by `langchain-google-vertexai`

**Comment by f-aguzzi** [comment]
@LorenzoPaleari I can confirm this. Closing as solved.
