### ISSUE TITLE
RateLimitError

### ISSUE THREAD

**Issue by RennanValadares** [ScrapeGraphAI/Scrapegraph-ai#595]
**Describe the bug**
I am receiving a RateLimitError meaning that the number of tokens is too high for my OpenAI account. 

When using gpt-4o-mini:
Exception has occurred: RateLimitError
Error code: 429 - {'error': {'message': 'Request too large for gpt-4o-mini in organization org-amMe on tokens per min (TPM): Limit 200000, Requested 395648. The input or output tokens must be reduced in order to run successfully. Visit https://platform.openai.com/account/rate-limits to learn more.', 'type': 'tokens', 'param': None, 'code': 'rate_limit_exceeded'}}

It is reaching the tokens per minute while requesting almost 400k tokens per minute. The issue with this is that one would need Tier2 in openai API to be able to use this lib.

**Expected behavior**
I would expect to be able to run this lib even with the lowest tier available on OpenAI. It should be slower yes, but still run.

**Comment by f-aguzzi** [comment]
Thanks for reporting this.

This adds more fuel to the fire of our discontent towards LangChain. It's a heavy dependency, it's slow to load and execute, yet we have to manually handle many low-level aspects (rate limits, context window sizes and chunking, ...).

I was having the same problem while testing the Mistral integration a few weeks ago. Their token rate limit is generous, but the API rejects individual requests if they come in at a rate of more than one per second. The fix for time rate limits is trivial through langchain, but the fix for token limits seems to be a little more complex.

We'll handle this as soon as the fixes for #593 and #594 will be published.

**Comment by datashaman** [comment]
Also seeing it. We are not using very much of the rate limit at all so the error is confusing.
Also it's reporting a strange org ID that I don't recognize in the error.
I suspect this is an issue with not adding project and organization to the client connection.

**Comment by f-aguzzi** [comment]
Proposed solution:

```mermaid
stateDiagram-v2
    [*] --> check_rate_limit

    state limit_rate_split <<fork>>
    check_rate_limit --> not_available : dictionary miss
    check_rate_limit --> limit_rate_split : dictionary hit (by provider)

    limit_rate_split --> limit_by_model : specific model available
    limit_rate_split --> limit_by_provider : only provider-wide info

    state limit_rate_join <<join>>
    limit_by_model --> limit_rate_join
    limit_by_provider --> limit_rate_join

    not_available --> [*] : do not put limit
    limit_rate_join --> [*] : impose limit

    note left of check_rate_limit
    rate_limit : dict
    - base_limit
    - models
    end note
```

The rate limit dictionary will look something like this:

```python
rate_limits = {
    "provider1": {
        "base_limit" : {
            "time_limit": 1,
            "token_limit": 200000
        },
       "models": {
           "model1" : {
               "time_limit": 0.3,
               "token_limit": 300000
            },
            "model2" : {
               "time_limit": 0.5,
               "token_limit": 200000
            },
    }
}
```

**Comment by f-aguzzi** [comment]
On top of this, I might add a generic exponential backoff retry to all models

**Comment by VinciGit00** [comment]
hi, please update to the new beta
