### ISSUE TITLE
ValueError: Provider gpt-4o-mini is not supported. If possible, try to use a model instance instead.

### ISSUE THREAD

**Issue by SumeraMartin** [ScrapeGraphAI/Scrapegraph-ai#603]
**Describe the bug**
I'm using the version 1.15.0-beta.7 and I'm not able to use gpt-4o-mini model. I noticed that there is required provider so I changed the model for openai/gpt-4o-mini and it started to work. So I think that this is just README issue.

**To Reproduce**
1. Install version 1.15.0-beta.7
2. Copy sample code from README
3. Execute it
4. Error

**Expected behavior**
There shouldn't be an error or readme should be updated.

**Comment by VinciGit00** [comment]
please update to the new beta

**Comment by f-aguzzi** [comment]
Oh, thanks for noticing this. I will update the readme ASAP.

Yeah, as you noticed, now the provider name is mandatory. Half of our recent issues were due to models being incorrectly associated with the correct API provider, so we had to impose this restriction.

Thanks for taking interest in our library and for reporting this.
